openapi: 3.0.1
info:
  title: Auth Service API
  version: 1.0.0
paths:
  /auth/register:
    post:
      summary: Регистрация пользователя
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: Пользователь зарегистрирован
  /auth/login:
    post:
      summary: Вход пользователя
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Успешный вход
  /auth/refresh:
    post:
      summary: Обновление токена
components:
  schemas:
    RegisterRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        fullName:
          type: string
    LoginRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
